package application;

import javafx.fxml.FXML;

import javafx.scene.control.Button;

import javafx.event.ActionEvent;

public class chatLo {
	@FXML
	private Button enviar;

	// Event Listener on Button[#enviar].onAction
	@FXML
	public void enviarMissatge(ActionEvent event) {
		// TODO Autogenerated
	}
}
